### ISSUE TITLE
A request from your reader

### ISSUE THREAD

**Issue by hurry-hub** [xaCheng1996/VFD#1]
Dear Harry Cheng,

Sorry to be a bother. I am an under-graduate from Wuhan University. Recently, I read your paper titled as "Voice-Face Homogeneity Tells Deepfake" and I am very interested in it.

Presently, I am researching some related issues, and I wonder if you can send me your codes or executive files which would give me a great of help in comprehending your algorithm and making some comparisons with mine. I will be appreciated for your reply as soon as possible, thank you very much!

Best regards,

Hurry Rechard

-------------------------------------------------------
Here is my email: whu_hurry@163.com

**Comment by xaCheng1996** [comment]
We have emailed you with some details of this work. Please check it and feel free to respond.
