### ISSUE TITLE
distance threshold

### ISSUE THREAD

**Issue by Jian00** [xaCheng1996/VFD#4]
你好，跑test_DF.py脚本时输出的距离都是1000+，但你的论文中取的距离阈值是300，请问这两个是一个东西吗

**Comment by xaCheng1996** [comment]
This threshold is used to calculate the ACC, i.e., the video is considered real when the voice-face distance is less than the threshold. The threshold is chosen in a fixed step in the validation set (which is stated in our manuscript).

We also consider that this threshold may change if the dataset is changed. We thus provide a simple regularization method, i.e., minus the minimum distance of all samples. Alternatively, you can directly compare the AUC without external thresholds.
(这个阈值在计算ACC时使用，当视频的voice-face距离小于阈值时，该视频被视为真视频。正如我们在论文中说明的，这个阈值是按照固定的步幅在验证集中选择的。
我们也考虑到如果更换数据集，这个阈值可能会变化，因此我们给出了一个简单的正规化方法，即减去所有样例中的最小值。或者您也可以直接比较AUC，这不需要外部阈值。)
